<script lang="ts">
	import '@fontsource-variable/dm-sans';
	import '@fontsource/dm-serif-display';
	import '../app.css';
	import { onMount } from 'svelte';
	import { pwaInfo } from 'virtual:pwa-info';
	import ReloadPrompt from '$lib/components/ReloadPrompt.svelte';
	import { getLocale } from '$lib/paraglide/runtime';
	import { trackInstallability } from '$lib/pwa.svelte';

	let { children } = $props();

	const webManifestLink = pwaInfo ? pwaInfo.webManifest.linkTag : '';

	onMount(() => {
		document.documentElement.lang = getLocale();
		return trackInstallability();
	});
</script>

<svelte:head>
	<!-- eslint-disable-next-line svelte/no-at-html-tags -- static tag generated by vite-pwa -->
	{@html webManifestLink}
</svelte:head>

{@render children()}

<ReloadPrompt />
